<<echo=FALSE, results=hide>>=
##MARCELO C.

r <- sample(seq(2,4,0.2),1)
V <- sample(c(12,110,120,127,220),1)
i <- round(sample(seq(0.5*V/r,0.8*V/r,0.5),1),1)

resp1=V-r*i

options(OutDec=",")
@

\begin{question}

Qual será a força contraeletromotriz de um receptor elétrico que possui resistência interna de $\Sexpr{r} \: \Omega $ , quando submetido a uma ddp de $\Sexpr{V} \: V$ e percorrido por uma corrente elétrica de $\Sexpr{i} \: A$?

\end{question}

<<echo=FALSE, results=hide>>=
options(OutDec=".")
@

\begin{solution}
%% Supply a solution here!

 \Sexpr{resp1} $ohms$

\end{solution}

%% META-INFORMATION
%% \extype{num}
%% \exsolution{\Sexpr{resp1}}
%% \exname{Q04receptores}
%% \extol{\Sexpr{0.01*resp1}}
